### ISSUE TITLE
Correção de Bugs

### ISSUE THREAD

**Issue by oLeall99** [GiovanniMoreira1/lista_de_tarefas#1]
- [x] **(1 ponto)** Os valores de categoria e descrição estão com quebra de linha no final da string. Adicione o código necessário para que esta quebra de linha não seja armazenada;
  - [x] **(1 ponto)** O valor da prioridade não está limitado entre 1 e 10;
  - [x] **(1 ponto)** Os erros não foram tratados na função main;
  - [x] **(1 ponto)** Os tamanhos da categoria e descrição na função de criar tarefas e na descrição do struct estão com os valores definidos, mas não usam uma variável ou parâmetro para isso. Use o #define para mudar estes valores;

**Comment by ArturChaves** [comment]
ERROS criar(Tarefa tarefas[], int *pos){
    if(*pos >= TOTAL)
        return MAX_TAREFA;

    do {
  printf("Entre com a prioridade |1 - 10|: ");
  scanf("%d", &tarefas[*pos].prioridade);
  } while (tarefas[*pos].prioridade > 10 || tarefas[*pos].prioridade < 1);
  
    clearBuffer();
    printf("Entre com a categoria: ");
    fgets(tarefas[*pos].categoria, 100, stdin);
    tarefas[*pos].categoria[strcspn(tarefas[*pos].categoria, "\n")] = '\0';
    printf("Entre com a descricao: ");
    fgets(tarefas[*pos].descricao, 300, stdin);
     tarefas[*pos].descricao[strcspn(tarefas[*pos].descricao, "\n")] = '\0';


    *pos = *pos + 1;

    return OK;
}


bug fix do criar tarefas
